spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://103.145.5.144:3306/food_store?serverTimezone=GMT%2B7&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
    username: food_store
    password: food_store
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  flyway:
    encoding: UTF-8
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ntp1102@gmail.com
    password: Hong@790
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  file:
    upload-dir: upload-file
  base-url: https://toeic.gogitek.online/files/

server:
  port: 6699

email:
  sender: reply
  success: Send email sucessfully!
  fail: Send email fail!

springfox:
  documentation:
    enabled: true
    open-api:
      enabled: true
    swagger-ui:
      enabled: true
    swagger:
      v2:
        path: /swagger-ui
        use-model-v3: true
        enabled: true